@startuml WorkerMessaging
skinparam Style strictuml
participant start as ":StartButton"
participant stop as ":StopButton"
participant controller as ":Controller" 
participant worker as ":Worker" <<(W,#ADD1B2)>>
autoactivate on

create worker
controller --> worker : create
start -> controller : click
controller -> worker : do simulation
deactivate controller
stop -> controller : click
activate controller
controller -> worker !! : terminate
create worker
controller --> worker : create

@enduml