@startuml WorkerMessaging
skinparam Style strictuml
participant start as ":StartButton"
participant stop as ":StopButton"
participant controller as ":Controller" 
participant worker as ":Worker" <<(W,#ADD1B2)>>
participant worker2 as ":Worker" <<(W,#ADD1B2)>>

'create worker
controller --> worker ** : create
start -> controller : click
activate controller
controller -->> worker : do simulation
deactivate controller
activate worker
deactivate controller

worker -->> controller : update
activate controller
deactivate controller

worker -->> controller : update
activate controller
deactivate controller

stop -> controller : click
activate controller
controller -> worker !! : terminate

create worker2
controller --> worker2 : create

deactivate controller

@enduml